name: Go

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  unit_testing:
    name: "Unit Testing"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          cache: true
          check-latest: true
          go-version: "${{ matrix.golang }}"
      - name: "Perform Unit Test"
        run: "go test -v ./..."

    strategy:
      matrix:
        golang:
          - 1.15
          - 1.16
          - 1.17
          - 1.18
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
